kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

pipeline:
  build:
    image: golang
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.io"
      CGO_ENABLED: 0
    commands:
      - go test ./...
      - go build

  publish:
    image: plugins/docker
    dockerfile: ./Dockerfile
    registry: registry.cn-shenzhen.aliyuncs.com
    repo: registry.cn-shenzhen.aliyuncs.com/liuyuexclusive/future.srv.basic
    username: "liuyuexclusive@hotmail.com"
    password: "a1234567"
    tags:
      - latest   

  # deploy:
  #   image: appleboy/drone-ssh # 用于连接服务器
  #   host: 
  #     - 172.16.60.48
  #   port: 22
  #   username: aaa
  #   password: bbb
  #   script:
  #     - export PATH=/usr/local/bin:$PATH
  #     - docker stop future.srv.basic_1
  #     - docker rm future.srv.basic_1
  #     - docker run -d --net=utils_default --name=future.srv.basic_1 registry.cn-shenzhen.aliyuncs.com/liuyuexclusive/future.srv.basic:latest