Name: "srv.basic"
Lease: 5
IP: 192.168.1.47
Port: "8080"
Address: ""
ConnStr: host=192.168.1.47 port=5432 password=123456 sslmode=disable user=postgres dbname=evolve
ElasticURL: http://192.168.1.47:9200
ETCDAddress: 
  - 192.168.1.47:2379
JaegerAddress: 192.168.1.47:6831
NatsAddress: 192.168.1.47:4222
RedisAddress: 192.168.1.47:6379
LogPath: "./log"
LogLevel: "debug"
AuthServiceName: "srv.auth"
TLS: 
  CertFile: "../../ssl/server_cert.pem"
  KeyFile: "../../ssl/server_key.pem"
  CACertFile: "/Users/wen/golang/utils/ssl/server_ca_cert.pem"
  ServerNameOverride: "test.example.com"

